services:

  postgres-db:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jooq-demo
    ports:
      - "5432:5432"
    volumes:
      - ./config/docker/postgresql/01_database_init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - demo-net

networks:
  demo-net:
    driver: bridge

volumes:
  postgres_data: {}

